build-and-publish-latest:
  runs-on: ubuntu-latest
  if: github.ref == 'refs/heads/master' # Running this job only for master branch

  steps:
    - uses: actions/checkout@v2 # Checking out the repo

    - name: Set up JDK 1.11
       uses: actions/setup-java@v1
       with:
         java-version: 1.11

    - name: Build with Maven
      run: mvn -B package --file pom.xml

